module.exports.fName = [
    'Hyper',
    'Coding',
    'Protocols',
    'Markup',
    'Data',
    'Abstraction',
    'Inheritence',
    'Polymorphism',
    'Codechef',
    'Hackerank',
    'C++',
    'Forest',
    'Ancient',
    'Petrified',
    'Roaring',
    'Cascade',
    'Tumbling',
    'Silent',
    'Redwood',
    'Bullfrog',
    'Maple',
    'Misty',
    'Elk',
    'Grizzly',
    'Ocean',
    'Sea',
    'Sky',
    'Dusty',
    'Diamond'
]

module.exports.lName = [
    'Text',
    'HTML',
    'CSS',
    'Javascript',
    'NodeJS',
    'reactJS',
    'NPM',
    'Express',
    'Web',
    'Java',
    'Development',
    'Flats',
    'Village',
    'Canyon',
    'Pond',
    'Group Camp',
    'Horse Camp',
    'Ghost Town',
    'Camp',
    'Dispersed Camp',
    'Backcountry',
    'River',
    'Creek',
    'Creekside',
    'Bay',
    'Spring',
    'Bayshore',
    'Sands',
    'Mule Camp',
    'Hunting Camp',
    'Cliffs',
    'Hollow'
]